### ISSUE TITLE
How to use lightbox?

### ISSUE THREAD

**Issue by c3rberus** [jhvanderschee/hugocodex#16]
I am trying to use the lightbox add-on, saved the js/css but I am confused with step 3 (modifying footer of your layout document looks like this:). What file do we need to add this in? I am using the smigle hugo theme and your image gallery add-in, tried adding it to  themes\smigle\layouts\partials\footer.html but no go. 

Can you provide more instructions for step 3?

**Comment by jhvanderschee** [comment]
I would add it in the footer of this one: https://github.com/rosorio/smigle-hugo-theme/blob/main/layouts/_default/baseof.html
