### ISSUE TITLE
Breadcrumb modification

### ISSUE THREAD

**Issue by pensivedog** [jhvanderschee/hugocodex#8]
Hello, I like your breadcrumbs solution and have implemented it on my site. Just one thing I would like to modify, I'm hoping you can help with, as I'm new to Hugo.

I would like for the current page - i.e., the one at the end of the breadcrumb tree - to not be a link.

Might you be able to suggest how to achieve this?

Thanks for your excellent work!

**Comment by jhvanderschee** [comment]
May I ask why?
