### ISSUE TITLE
adding 'class' depending on page Type/Layout condition ?

### ISSUE THREAD

**Issue by fenix011** [jhvanderschee/hugocodex#9]
I'm facing a layout to be styled with a CSS class addition upon condition issue here at the hugocodex with

```
  <body class="{{ .Type }} {{ .Layout }}">
```

  By reading [An 's question on the forum](https://discourse.gohugo.io/t/add-css-class-depending-on-layout-type/1989)i have a debugging starting point.
Now i know that by adding :

```
{{ printf "%#v" . }}
```
I can easily read the list of all the variables scoped to the current context (., aka “the dot”).
In my use case, 

```
{{ printf "%#v" .Layout }}
```

Will tell which layout is in use on a page!
It looks like we are missing the Layout definition (!) somehow, as long that it is not shown... but on the other hand that page is using the layouts/products/single default.html one ? what am i missing ?

Thanks, thanks, thanks

**Comment by jhvanderschee** [comment]
We do not use layouts anymore... that was more of a Jekyll approach. What class are you trying to create? On which page?

**Comment by fenix011** [comment]
Ah, no Layouts based logic anymore in Hugo. Lesson learned.
If i've well understood... [then we could rid of this condition here ?](https://github.com/jhvanderschee/hugocodex/blob/003867d1cdbbcdce043688a1ceab91f7752b407f/layouts/partials/header.html#L34)
It's on the product page we need to add the CSS class.

**Comment by jhvanderschee** [comment]
you can add it with .IsHome
